# Generated by Django 2.1.1 on 2019-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0005_auto_20190211_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial_usuario',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
