# Generated by Django 2.1.1 on 2019-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0006_auto_20190213_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial_emisora',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
