# Generated by Django 2.1.1 on 2019-03-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0007_auto_20190213_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='isConcurso',
            field=models.BooleanField(default=0),
        ),
    ]
